[package]
name = "svc-utils"
version = "0.2.0"
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/svc-utils"
repository = "https://github.com/foxford/svc-utils-rs"
description = "Bunch of reusable utilities"

[features]
authn-extractor = ["svc-authn", "svc-agent"]
body-limit-middleware = []
cors-middleware = []
log-middleware = []
metrics-middleware = ["once_cell"]

[dependencies]
axum = "0.4"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14.15", features = ["server"] }
prometheus = { version = "0.13", default-features = false }
tokio = { version = "1.14", features = ["sync"] }
tower = "0.4"
tower-http = { version = "0.2.3", features = ["trace"] }
tracing = "0.1"
svc-authn = { version = "0.7", features = ["jose"], optional = true }
svc-agent = { version = "0.19.4", optional = true }
once_cell = { version = "1.9", optional = true }

[dev-dependencies]
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
tokio = { version = "1.14", features = ["full"] }
tracing-subscriber = "0.3"
tracing-futures = "0.2"

[[example]]
name = "http_metrics"
