[package]
name = "svc-utils"
version = "0.1.0"
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/svc-utils"
repository = "https://github.com/foxford/svc-utils-rs"
description = "Bunch of reusable utilities"

[dependencies]
axum = "0.2"
hyper = { version = "0.14", features = ["server"] }
prometheus = "0.13"
tokio = { version = "1", features = ["sync"] }
tower-http = { version = "0.1", features = ["trace"] }
tracing = "0.1"

[dev-dependencies]
futures = "0.3"
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[[example]]
name = "http_metrics"
